name: Deployment Pipeline

on:
  push:
    branches:
      - develop
      # - deployment
jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' 

      - name: Install Dependencies
        run: go mod download

      # - name: Run Tests
      #   run: go test ./... -v

      - name: Build Project
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server ./cmd/api/main.go
          ls -lah
      
      - name: Copy Binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: "server" 
          target: "/home/ubuntu/"

      - name: Restart Systemd Service on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            
            mv /home/ubuntu/server /home/ubuntu/tasksy-server
            chmod +x /home/ubuntu/tasksy-server
            sudo systemctl restart tasksy-server.service
            sudo systemctl status tasksy-server.service --no-pager