name: Deployment Pipeline

on:
  push:
    branches:
      - working
      # - deployment

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' 

      - name: install project dependencies
        run: go mod download

      - name: build binaries
        run: |
          # 1. Build API Server
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server ./cmd/api/main.go
          
          # 2. Build Worker (Add this line)
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o worker ./cmd/worker/main.go
          
          ls -lah
      
      - name: copy binaries to vps
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          # Upload BOTH files (comma separated)
          source: "server,worker" 
          target: "/home/ubuntu/"

      - name: restart linux systems services
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Move Server Binary
            mv /home/ubuntu/server /home/ubuntu/tasksy-server/server
            chmod +x /home/ubuntu/tasksy-server/server
            
            # Move Worker Binary
            mv /home/ubuntu/worker /home/ubuntu/tasksy-server/worker
            chmod +x /home/ubuntu/tasksy-server/worker

            # Restart BOTH Services
            sudo systemctl daemon-reload
            sudo systemctl restart tasksy-server.service
            sudo systemctl restart tasksy-worker.service
            
            # Check Status
            sudo systemctl status tasksy-worker.service --no-pager
